# Project
version=1.0.0-dev
group=com.tracel
# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=768m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Kotlin
kotlin.incremental=true
kotlin.caching.enabled=true
kotlin.code.style=official
