[versions]
kotlin = "2.4.20"
kotlinpoet = "2.4.0"
ksp = "2.3.12"
coroutines = "1.11.0"
collections-immutable = "0.5.2"
atomicfu = "0.33.0"
caffeine = "3.3.0"
semver = "3.1.0"
tomlj = "2.1.1"
zstd = "1.5.7-16"
shadow = "9.6.1"
hdrhistogram = "2.2.2"
konsist = "0.17.3"
junit = "6.1.3"
sqlite = "3.53.4.0"
paper = "26.1.2.build.74-stable"
runPaper = "3.1.0"
hangarPublish = "0.1.4"
fawe = "2.15.3"
bstats = "3.2.1"
luckperms = "5.4"

[libraries]
build-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections-immutable" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
semver = { module = "io.github.z4kn4fein:semver-jvm", version.ref = "semver" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }
hdrhistogram = { module = "org.hdrhistogram:HdrHistogram", version.ref = "hdrhistogram" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
fawe-core = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Core", version.ref = "fawe" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
luckperms-api = { module = "net.luckperms:api", version.ref = "luckperms" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangarPublish" }
