package com.tracel.codegen

import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSNode

///** Constructs a [Dependencies] instance from the given originating source [files]. */
//internal fun dependencies(aggregating: Boolean = false, vararg files: KSFile?): Dependencies {
//    val present = files.filterNotNull().toTypedArray()
//    return if (present.isEmpty()) Dependencies(aggregating) else Dependencies(aggregating, *present)
//}

///** Convenience overload to construct [Dependencies] for a single originating source [file]. */
//internal fun dependencies(file: KSFile?, aggregating: Boolean = false): Dependencies =
//    dependencies(aggregating, file)
//
///**
// * Creates a new generated source file via [CodeGenerator.createNewFile] and writes the content
// * generated by [body].
// */
//internal fun CodeGenerator.writeGenerated(
//    deps: Dependencies,
//    pkg: String,
//    name: String,
//    body: StringBuilder.() -> Unit,
//) {
//    createNewFile(deps, pkg, name).bufferedWriter().use { it.write(buildString(body)) }
//}

/**
 * Logs a compilation error associated with [node].
 *
 * @return `null` if the error was logged.
 */
internal fun KSPLogger.fail(message: String, node: KSNode): Nothing? {
    error(message, node)
    return null
}
